services:
  backend:
    build:
      context: ./app_hernia
      dockerfile: Dockerfile.backend
    environment:
      - HIATAL_BUNDLE_PATH=/app/model/production_bundle.pt
    expose:
      - "8000"
    networks:
      - hernia-net

  frontend:
    build:
      context: ./app_hernia
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:5000"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - hernia-net
    links:
      - backend

networks:
  hernia-net:
    driver: bridge
