artifact_location: /home/ubuntu/maia_proyecto_desarrollo_soluciones/outputs/hiatal_mlflow/mlartifacts/313663386070990972
creation_time: 1771729427453
experiment_id: '313663386070990972'
last_update_time: 1771729427453
lifecycle_stage: active
name: hernia-hiatal-production
workspace: default
